sudo: yes
dist: trusty
language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - willemjanfaber@fe2.nl
    on_success: change
    on_failure: always
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libxml2-dev libdb-dev python2.7 python-pip python-virtualenv imagemagick jp2a duc
install:
  - bash install.sh
script:
  - bash run-tests.sh
